image: openjdk:14

stages:
    - build
    - test

build:
    stage: build
    script: /usr/java/openjdk-14/bin/javac /src/kiosk/Kiosk.java

test:
    stage: test
    script: echo "This is where tests will happen."